"""Blockchain-specific constants and enumerations for KRITAGAS."""

from app.core.constants import StrEnum


class BlockchainMode(StrEnum):
    """Blockchain operation modes."""
    MOCK = "mock"
    ETHEREUM = "ethereum"


class BlockchainRecordStatus(StrEnum):
    """Status of a blockchain record."""
    PENDING = "PENDING"
    REGISTERED = "REGISTERED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class IntegrityStatus(StrEnum):
    """Evidence integrity verification status."""
    PENDING = "PENDING"
    REGISTERED = "REGISTERED"
    VERIFIED = "VERIFIED"
    TAMPERED = "TAMPERED"
    FAILED = "FAILED"


class RecordType(StrEnum):
    """Type of record stored on the blockchain."""
    EVIDENCE_HASH = "EVIDENCE_HASH"
    FIR_HASH = "FIR_HASH"
    OCR_RESULT_HASH = "OCR_RESULT_HASH"
    CASE_HASH = "CASE_HASH"
    AI_REPORT_HASH = "AI_REPORT_HASH"
    AGENT_REPORT_HASH = "AGENT_REPORT_HASH"
    NETWORK_SNAPSHOT_HASH = "NETWORK_SNAPSHOT_HASH"
    AUDIT_HASH = "AUDIT_HASH"
    CUSTODY_EVENT_HASH = "CUSTODY_EVENT_HASH"


class EntityType(StrEnum):
    """Entity types tracked by the blockchain integrity system."""
    FIR = "FIR"
    CASE = "CASE"
    EVIDENCE = "EVIDENCE"
    OCR_RESULT = "OCR_RESULT"
    AI_REPORT = "AI_REPORT"
    AGENT_REPORT = "AGENT_REPORT"
    INVESTIGATION_REPORT = "INVESTIGATION_REPORT"
    NETWORK_SNAPSHOT = "NETWORK_SNAPSHOT"
    CCTV_METADATA = "CCTV_METADATA"
    CDR_DATASET = "CDR_DATASET"
    FINANCIAL_DATASET = "FINANCIAL_DATASET"
    SOCIAL_MEDIA_EVIDENCE = "SOCIAL_MEDIA_EVIDENCE"


class CustodyEventType(StrEnum):
    """Chain of custody event types."""
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    EVIDENCE_ACCESSED = "EVIDENCE_ACCESSED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    EVIDENCE_TRANSFERRED = "EVIDENCE_TRANSFERRED"
    EVIDENCE_ANALYZED = "EVIDENCE_ANALYZED"
    EVIDENCE_ARCHIVED = "EVIDENCE_ARCHIVED"
    OCR_COMPLETED = "OCR_COMPLETED"
    AI_ANALYSIS_COMPLETED = "AI_ANALYSIS_COMPLETED"
    REPORT_GENERATED = "REPORT_GENERATED"
    TAMPER_DETECTED = "TAMPER_DETECTED"


class InvestigationAuditAction(StrEnum):
    """Blockchain-level investigation audit actions."""
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    FIR_UPLOADED = "FIR_UPLOADED"
    FIR_PROCESSED = "FIR_PROCESSED"
    OCR_EXECUTED = "OCR_EXECUTED"
    ENTITY_EXTRACTED = "ENTITY_EXTRACTED"
    ENTITY_RESOLVED = "ENTITY_RESOLVED"
    RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"
    NETWORK_GENERATED = "NETWORK_GENERATED"
    AI_AGENT_EXECUTED = "AI_AGENT_EXECUTED"
    AI_REPORT_GENERATED = "AI_REPORT_GENERATED"
    EVIDENCE_UPLOADED = "EVIDENCE_UPLOADED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    EVIDENCE_TAMPER_DETECTED = "EVIDENCE_TAMPER_DETECTED"
    CASE_REPORT_EXPORTED = "CASE_REPORT_EXPORTED"
    INTEGRITY_REGISTERED = "INTEGRITY_REGISTERED"
    CUSTODY_EVENT_CREATED = "CUSTODY_EVENT_CREATED"
